### PR TITLE
Fixes error not getting spotify-apicode when no daemon is running 

### PR DESCRIPTION
**Pull request by Kondamon**
See solution from here: https://github.com/maximilianvoss/spotify-toniebox-sync/issues/23#issuecomment-745261209

### CODE REVIEW

**Comment by kuglemic** [comment]
Thank you for the nice Pull request. Helps me a lot.

But I realised, that just typing in `./musicsync` doesn't print the help (which commands are available) anymore.

**Comment by Kondamon** [comment]
@kuglemic Thanks for reviewing it. Have added an option that detects if there are any arguments provided.

**Comment by ChristianRamseier** [comment]
+1 to go forward with the merge

**Comment by maximilianvoss** [comment]
Great fix, used it in the latest version

**Pull request closed without merging**
